### ISSUE TITLE
Some of the cron expressions are not supported

### ISSUE THREAD

**Issue by ashokmariyala** [reugn/go-quartz#13]
All cron expressions not supported 

Example
```
package main

import (
	"fmt"
	"strconv"
	"time"

	"github.com/reugn/go-quartz/quartz"
)


type ScheduledJob struct {
	jobid  int
	config string
}


func NewScheduledJob(jobid int, config string) *ScheduledJob {
	var job ScheduledJob
	job.jobid = jobid
	job.config = config
	return &job
}

func (sh *ScheduledJob) Description() string {
	return sh.config
}

func (sh *ScheduledJob) Key() int {
	return sh.jobid
}

func (sh *ScheduledJob) Execute() {
	fmt.Printf("Job id %s Config %s", strconv.Itoa(sh.jobid), sh.config)
	time.Sleep(2 * time.Second)
}

func main() {
	sched := quartz.NewStdScheduler()
	sched.Start()

	cronTrigger, err := quartz.NewCronTrigger("0 12 */2 * * ? *")

	if err != nil {
		fmt.Println(err)
		return
	}
	job := NewScheduledJob(10, "My config")
	sched.ScheduleJob(job, cronTrigger)

	<-make(chan int)
}
```
Error

> `Invalid cron expression: Cron step min/max validation error`

Above cron expression means every 2 hours

Additional cron expressions that are fail 
```
Every 3 hours : 0 24 */3 * * ? *
Every 4 hours : 0 43 */5 * * ? *
Every 6 hours : 0 54 */6 * * ? * 
Every 12 hours : 0 51 */12 * * ? *
Every 2 days 3rd hour: 0 0 3 */2 * ? *
Every 6 days 10th hour: 0 0 10 */6 * ? *
Every Month 2nd Monday 6th Hour: 0 0 6 ? * 2#2 *
Every Month 4th Tuesday 15th hour: 0 0 15 ? * 3#4 *
```
etc

**Comment by ashokmariyala** [comment]
@reugn Could you please verify the above issue and fix it. Thanks in advance.

**Comment by reugn** [comment]
@ashokmariyala thanks for your interest in `go-quartz`.
The asterisk issue in the step value has been fixed in v0.3.5.
Other than that, below is the table of unsupported characters (comparing to Quartz) in an expression:
Field | Unsupported Characters
--- | ---
Day of month | L W C
Day of week | L C #
Year | , - /

**Comment by ashokmariyala** [comment]
@reugn Thank you for your quick response. I am still facing the asterisk issue in the Day of month field.

```
0 0 3 */2 * ? * ==> Every 2 days 3rd hour
0 0 6 */4 * ? * ==> Every 4 days 6th hour
0 0 10 */6 * ? * ==> Every 6 days 10th hour
0 0 20 */10 * ? * ==> Every 10 days 20th hour
```
When can I expect # support in the Day of week field? 
Many thanks for considering my request.

**Comment by reugn** [comment]
@ashokmariyala
1. Please verify using this fix #15 
2. I do not plan to add support for the missing expression characters in the near future. Any contribution is welcome.

**Comment by ashokmariyala** [comment]
@reugn Thank you for your quick response. Using the above fix, Day of month field also working fine. Please push your changes.

**Comment by ashokmariyala** [comment]
@reugn When I used `go get github.com/reugn/go-quartz@v0.3.5`, I didn't receive the latest fix details in my local. Also, I tried to download the v0.3.5 source code; the latest fix details are not there. Have I missed anything here?

**Comment by reugn** [comment]
@ashokmariyala take the latest commit at the moment, and I'll release the next version shortly.

**Comment by ashokmariyala** [comment]
@reugn I observed sometimes scheduling is stopped in the middle of scheduling a job without giving any error. I encountered this issue 2 times (1st time after 8 hours of Job Scheduling and 2nd time after 3 hours of Job scheduling). Is there any way to debug to find what the exact problem is?

**Comment by reugn** [comment]
@ashokmariyala please see the develop branch.

**Comment by ashokmariyala** [comment]
@reugn I couldn't find [use the minimum available value in case of asterisk (#15) ](https://github.com/reugn/go-quartz/pull/15/commits/6daf12eab747a32f13af7456b157ad87bb163927) fix details in  v0.3.5 version.

**Comment by ashokmariyala** [comment]
@reugn Thank you for your response. I will take develop branch and validate.

**Comment by reugn** [comment]
@ashokmariyala v0.3.6 has been released.

**Comment by ashokmariyala** [comment]
Thanks @reugn
